### ISSUE TITLE
Doesn't work on Version ⁨2.1.49 (dc80804a)⁩

### ISSUE THREAD

**Issue by Sandy4846** [glutanimate/speed-focus-mode#51]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

![image](https://user-images.githubusercontent.com/111045758/184088933-61fcd88f-4cbc-4a8a-b39d-5637be17a538.png)

Installation done with copying the setup configuration as above. But no auto alarm nor auto answering.

![image](https://user-images.githubusercontent.com/111045758/184089611-5be47967-863f-46c2-8153-4b9e779f780a.png)

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*
No error message.

```python

```

**Comment by Sandy4846** [comment]
Traceback (most recent call last):
  File "aqt\webview.py", line 41, in cmd
  File "aqt\webview.py", line 142, in _onCmd
  File "aqt\webview.py", line 595, in _onBridgeCmd
  File "C:\Users\kchen\AppData\Roaming\Anki2\addons21\1136455830\Bottom_Bar.py", line 94, in linkHandler_wrap
    Card_Info._cs.toggle()
  File "C:\Users\kchen\AppData\Roaming\Anki2\addons21\1136455830\Card_Info.py", line 72, in toggle
    self.show()
  File "C:\Users\kchen\AppData\Roaming\Anki2\addons21\1136455830\Card_Info.py", line 61, in show
    self._update()
  File "C:\Users\kchen\AppData\Roaming\Anki2\addons21\1136455830\Card_Info.py", line 384, in _update
    txt += d.cardStats_mod(current_card)
  File "C:\Users\kchen\AppData\Roaming\Anki2\addons21\1136455830\Card_Info.py", line 320, in cardStats_mod
    return CardStats(self, card).report_mod()
  File "C:\Users\kchen\AppData\Roaming\Anki2\addons21\1136455830\Card_Info.py", line 222, in report_mod
    self.addLine("Created", time.strftime("%Y-%m-%d | %H:%M", time.localtime(c.id/1000)))
OSError: [Errno 22] Invalid argument

**Comment by Sandy4846** [comment]
It works after deleting "1136455830" add-on, but I want to use both adds-on. So still need your help. Thanks

**Comment by Sandy4846** [comment]
![image](https://user-images.githubusercontent.com/111045758/184092559-d0af9032-7bf2-4e63-adce-0bfe7e885c93.png)

**Comment by Sandy4846** [comment]
Additional bug information.

**Comment by Elias-Yona** [comment]
> ![image](https://user-images.githubusercontent.com/111045758/184092559-d0af9032-7bf2-4e63-adce-0bfe7e885c93.png)

I'm getting the same error when I try to exit Anki while the addon is still running. My anki version is 2.1.54
