### ISSUE TITLE
Error when clicking on "Browse" in Anki with Speed Focus Beta enabled

### ISSUE THREAD

**Issue by dhruchainz** [glutanimate/speed-focus-mode#54]
#### Problem description

I am not sure what exactly the effect of this error is, but every time I click on Browse, I get notification for an error. It suggests I disable all addons and toggle each one until the error appears to identify the problematic addon. I identified the Speed Focus beta addon to be the issue. I am currently running Anki 2.1.54 qt6 on Windows 11. 

Also, thank you so much for this addon. It has singlehandedly been the most helpful thing to improve my performance.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    
    Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2022-10-04 11:51:37
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Anki Simulator ['817108664', 2021-08-07T14:24, 'None', '']
    Image Occlusion Enhanced for Anki 21 ['1374772155', 2022-04-09T02:15, 'None', '']
    Review Heatmap ['1771074083', 2022-06-29T20:43, 'None', '']
    Speed Focus Mode ['speed_focus_mode', 2019-06-28T17:35, 'None', '']
    Symbols ['1461102936', 2019-04-18T15:21, 'None', mod]
    Syntax Highlighting for Code ['1463041493', 2018-10-06T20:31, 'None', '']
    True Retention ['613684242', 2017-11-19T14:43, 'None', '']
    Web Browser - Search terms Import texts and images automatically ['864545277', 2022-08-02T15:49, 'None', '']
    right hand reviews  hjkl answer shortcuts  Handy Answer Keys configurable ['850294128', 2021-12-06T09:00, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1374772155 1461102936 1463041493 1771074083 613684242 817108664 850294128 864545277
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-10-04 11:51:37

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 624, in _onBridgeCmd
  File "aqt.toolbar", line 168, in _linkHandler
  File "aqt.toolbar", line 186, in _browseLinkHandler
  File "aqt.main", line 1138, in onBrowse
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 81, in repl
TypeError: onDialogOpened() got an unexpected keyword argument 'card'

```

**Comment by weirdalsuperfan** [comment]
I also get this error!!!
